### ISSUE TITLE
Is a possible to install a light version with only the netSmooth function

### ISSUE THREAD

**Issue by sqjin** [BIMSBbioinfo/netSmooth#15]
Hello,
I am interested to apply netSooth to my scRNA-seq data. To install this package, it requires a higher version of 'scater' pacakge and there is an error to install 'glmnet' (package ‘glmnet’ is not available (for R version 3.5.3)). I am wondering if there is a light version I can install to perform the basic smooth function. For a light version, I will only use netSooth and will not use any other plot functions.   Thanks so much!

**Comment by jonathanronen** [comment]
Hi @sqjin. Unfortunately, we don't have a "netSmooth lite" with fewer dependencies. How are you installing netsmooth on R 3.5.3? All the dependencies should work, if you install using bioconductor.

**Comment by sqjin** [comment]
@jonathanronen Hello, Yes, I used bioconductor. Please see error below: 
Loading required package: clusterExperiment
Error: package or namespace load failed for ‘clusterExperiment’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
  there is no package called ‘glmnet’
Error: package ‘clusterExperiment’ could not be loaded

It looks like glmnet does not work for R 3.5.3. 

> install.packages("glmnet", repos = "https://cran.us.r-project.org")
Warning in install.packages :
  package ‘glmnet’ is not available (for R version 3.5.3)

**Comment by rekado** [comment]
sqjin <notifications@github.com> writes:

> It looks like glmnet does not work for R 3.5.3.
>
>> install.packages("glmnet", repos = "https://cran.us.r-project.org")
> Warning in install.packages :
>   package ‘glmnet’ is not available (for R version 3.5.3)

The current version of glmnet requires R 3.6.0 or greater.  You can
manually install an older version.  Older source tarballs are archived
here:

    https://cran.r-project.org/src/contrib/Archive/glmnet/

I can’t promise it’ll work within the context of netSmooth and its
dependencies, but if you absolutely must use R 3.5.3 you can give this a
try.

--
Ricardo

**Comment by sqjin** [comment]
@jonathanronen @rekado Thanks so much for your help. It works now after I installed package ‘glmnet’ version 2.0-18. 

Sorry, I have one more question. When I tried to build a light version of netSmooth package (i.e., only running x.smoothed <- netSmooth(x, adj_matrix, alpha=0.5)) in my local computer,  it cannot pass the "checking" step due to the warning "Undocumented arguments in documentation object 'netSmooth,matrix-method'".  Do you have any idea on how to document this object?  I think I have kept all the necessary documentations in the original package. Thanks!

**Comment by jonathanronen** [comment]
@sqjin glad it worked! Thanks, @rekado.

Re: `Undocumented arguments...`. If you can't find the answer, perhaps here [1], maybe you could show me your documented function?

[1]: http://r-pkgs.had.co.nz/man.html#man-functions

**Comment by sqjin** [comment]
@jonathanronen Thanks! For some reasons, it works now. You might can help to take a quick look if you get any chance. Here is the light version I created "https://github.com/sqjin/netSmooth". The basic idea is to only output the imputed data matrix for a given alpha. Thus I removed other unnecessary functions such as the methods for inferring alpha.

**Comment by jonathanronen** [comment]
Great! Thanks for getting in touch and for putting this light version out there! :beers:

I am now closing this issue, but please feel free to open a new if you have more questions.
