### ISSUE TITLE
Issues when processing large matrix

### ISSUE THREAD

**Issue by kobeho24** [BIMSBbioinfo/netSmooth#7]
Hi,
I tried to netsmooth my scRNAseq data, 15141 X 6518. I have the following error messages when dealing with sparse matrix and the dense matrix converted.
musc.ns <- netSmooth(musc.data, mouse.ppi, alpha = 0.5, numcores = 2)
Using given alpha: 0.5
Error: cannot allocate vector of size 1.1 Gb

or

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘netSmooth’ for signature ‘"dgTMatrix"’

or

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘netSmooth’ for signature ‘"dgCMatrix"’

Any solutions?

**Comment by jonathanronen** [comment]
Thanks for reporting this. I've encountered this too and will publish a fix soon.

**Comment by kobeho24** [comment]
Appreciate that! And I wonder if netSmooth can handle sparse matrix in the upcoming version. It appears that mouse.ppi is a sparse matrix, if the expression matrix input can also be sparse, that would be great!

**Comment by jonathanronen** [comment]
I just pushed some changes that should support sparse matrices as inputs, thanks for the idea!

Please use the `bioconductor_3_6` branch, as the `master` branch just diverged a little in order to support the next bioconductor release.

Let me know if it works and we can close this issue!

**Comment by kobeho24** [comment]
error comes up when setting alpha='auto'
musc.ns <- netSmooth(musc.data, mouse.ppi, alpha = 'auto', numcores = 3)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘pickDimReduction’ for signature ‘"dgCMatrix"’

**Comment by kobeho24** [comment]
setting alpha to a fix num works fine, e.g. 0.5

**Comment by jonathanronen** [comment]
You should now be able to use `alpha='auto', autoAlphaMethod='entropy'`. It will not work with `autoAlphaMethod='robustness'` (the default) as that method depends on another package (`clusterExperiment`) which does not support sparse input matrices.

Hope that helps!

**Comment by kobeho24** [comment]
what's the difference between 'entropy' and 'robustness'

**Comment by jonathanronen** [comment]
Robustness attempts to cluster the data using a procedure that ommits data points that don't fall into a robust cluster. See the section "Optimizing the smoothing parameters by cluster robustness" in the paper https://f1000research.com/articles/7-8/v2.

Entropy uses the entropy in a 2D embedding to pick the best value of alpha, see the section "Choice of dimensionality reduction technique in the clustering procedure" in the paper for how it works.

Neither algorithm can effectively guarantee the best alpha will be picked for your particular analysis, but they are our best effort. If you have any other ideas on how alpha might be picked algorithmically, we're happy to hear suggestions :-)

**Comment by kobeho24** [comment]
It worked, thx. But I still got some questions about netSmooth. Since I am handling UMI-based data, do I need to normalized it before smoothing? And for the resulting output, is it a normalized (tpm equivalent) matrix?

**Comment by jonathanronen** [comment]
In my experience it works best with normalized counts as input. You may view the output as equivalent to the input in data type, i.e. if the input was normalized TPM, the output is equivalent to that; if the input was log counts, the output is equivalent to that.

**Comment by kobeho24** [comment]
Just wonder, how long does it usually take for the smoothing? It has been over 24 hours since I started the program for smoothing my large matrix on HPC. Using 8 cores but it appears only 4 has been used.

**Comment by jonathanronen** [comment]
Sorry, I don't have a comprehensive benchmark for such large data sets. How long did it eventually take?
