### ISSUE TITLE
get NAN result using function netSmooth

### ISSUE THREAD

**Issue by nikouseven** [BIMSBbioinfo/netSmooth#8]
Hello， I  have the following problems when i use the package netSmoth, I hope to get your help:
**input** 

1. single cell expression data  (data.frame), row name is gene symbol, col nams is cell or sample names， 
2. PPI netwrok from string database, gene name is gene symbol (following buidingPPIsFromStringDB.R )

**output**
when i use function `after = netSmooth(data, network, alpha=0.5),`  no error was reported during the operation, but the result was a lot of NAN, such as 
`> head(after)`
         L128_B01 L128_C01 L128_D01 L128_E01 L128_F01 L128_G01 L128_H01 L128_B02
CFTR          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
         L128_C02 L128_D02 L128_E02 L128_F02 L128_G02 L128_H02 L128_A03 L128_B03
CFTR          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
         L128_D03 L128_E03 L128_F03 L128_G03 L128_H03 L128_A04 L128_B04 L128_C04
CFTR          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
         L128_D04 L128_E04 L128_F04 L128_G04 L128_H04 L128_A05 L128_B05 L128_C05

  However,  the reslut looks great when i use example data (smallPPI、smallscRNAseq).  I don't know why thid problem is happing, I hope I get your help

**Comment by jonathanronen** [comment]
Thanks for the report, @nikouseven. Could you provide me with an example dataset (as small as possible) and script that reproduce this? Without that it would be difficult for me to troubleshoot.

**Comment by nikouseven** [comment]
[exampleData.zip](https://github.com/BIMSBbioinfo/netSmooth/files/2155194/exampleData.zip)
Hello Jona:
  1、my example data is added in the attachment;
  2、my script as following:
  load("smalldata.RData")
  load("samllPPI.RData")
  after <- netSmooth(smalldata, as.matrix(smallPPI), alpha=0.5)
  head(after)
#> head(after)
#L128_B01 L128_C01 L128_D01 L128_E01 L128_F01 L128_G01 L128_H01 L128_B02 L128_C02 L128_D02
#CFTR          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
##USP28         NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
#MEM176A      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN

**Comment by jonathanronen** [comment]
The problem with the `smallPPI` you're providing is that it has some genes with no connections in the network, i.e. rows/columns in `smallPPI` that are all 0s. The following works:

```r
smallPPI.nonzero <- smallPPI[which(!Matrix::rowSums(smallPPI)==0),which(!Matrix::rowSums(smallPPI)==0)]
after <- netSmooth(smalldata, as.matrix(smallPPI.nonzero), 0.5)
```
---------

Thanks, for reporting this :beer:  I should make the code give a meaningful error on this case rather than just fail miserably.

**Comment by nikouseven** [comment]
Dear Jona:
   Thank you for your help. I also found the same problem yesterday. According to your solution, my problem is solved very well.  The package netSmooth is great for single cell data analysis. AS a beginner, we may use  the example PPI data  as input (human.ppi or mouse.ppi),  So I think you can modify related functions in netSmooth to avoid this problem.  Thank you very much！

**Comment by jonathanronen** [comment]
Thanks, @nikouseven!

This is fixed so that after the next release, anybody encountering a similar issue will be shown an informative error message.
